### ISSUE TITLE
Add the posibility to stream IMU data at the desired rate

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/yarp-device-xsensmt#33]
The current implementation of the [`xsensmt` device](https://github.com/robotology/yarp-device-xsensmt/tree/master/xsensmt) allows for streaming at ~100Hz.

Quoting the comment from @traversaro in another location:

> ## IMU
> 
> > For some reason, the only file called is https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova04_higherFreq/iRonCub-Mk1/hardware/inertials/waist-inertial.xml which also open the waist IMU port
> 
> Some YARP Network Wrapper Server permit to open hardware devices via the `subdevice` parameter, and this is what is done in this case, see https://github.com/ami-iit/robots-configuration/blob/e1d22102852e72745a748635a9f0898be57decd9/iRonCub-Mk1/hardware/inertials/waist-inertial.xml#L8  . However, the period parameter that is read by the `inertial` YARP device is not read by the `xsensmt`  YARP device. The paremeters supported are not documented it seems, but can be found in https://github.com/robotology/yarp-device-xsensmt/blob/6de80ae7d3a67eb315d4972c2e2023d73cf2dc5a/xsensmt/XsensMT.cpp#L91 , and no `period`  parameter is read. The data is read by the `sensorReadLoop`, that is continuously receiving data from the serial connection to the sensor:
> * https://github.com/robotology/yarp-device-xsensmt/blob/6de80ae7d3a67eb315d4972c2e2023d73cf2dc5a/xsensmt/XsensMT.cpp#L217
> * https://github.com/robotology/yarp-device-xsensmt/blob/6de80ae7d3a67eb315d4972c2e2023d73cf2dc5a/xsensmt/XsensMT.cpp#L250
> * https://github.com/robotology/yarp-device-xsensmt/blob/6de80ae7d3a67eb315d4972c2e2023d73cf2dc5a/xsensmt/XsensMT.cpp#L324
> 
> If the data is coming at ~100 Hz, probably it is because the Xsens sensor is sending it at that rate: probably we should modify the driver to permit it to ask to the Xsens sensor to send it at higher frequency, probably modifying around this part of the code: https://github.com/robotology/yarp-device-xsensmt/blob/6de80ae7d3a67eb315d4972c2e2023d73cf2dc5a/xsensmt/XsensMT.cpp#L172. Se also Table 2 in http://web.archive.org/web/20211212143408/https://www.xsens.com/hubfs/Downloads/Manuals/MT_Low-Level_Documentation.pdf, it seems that with the profile in which we set the sensor the expected output is indeed 100 Hz. We could open an issue on this at https://github.com/robotology/yarp-device-xsensmt/issues .

It would be nice to have the possibility to make the period a configurable parameter.

**Comment by HosameldinMohamed** [comment]
We are testing this with IMU `MTi-100` (@traversaro can you confirm),

in this case setting the profile using `VRU_General` may not be relevant since in the table below we should look at the left side? 🤔 

![image](https://user-images.githubusercontent.com/45564317/170279167-4a152afe-28ed-4e23-a8ec-99e06e9f1270.png)

**Comment by HosameldinMohamed** [comment]
The part that sets the frequency seems in this part:

https://github.com/robotology/yarp-device-xsensmt/blob/7b9425c87797fb4f443bcab6838f755faece8472/xsensmt/XsensMT.cpp#L154-L157

Where we set the `identifier` then the `frequency`, and it seems we are hardcoding the frequency to `100Hz`.

See in the manual http://web.archive.org/web/20211212143408/https://www.xsens.com/hubfs/Downloads/Manuals/MT_Low-Level_Documentation.pdf in page 30, this part:

![image](https://user-images.githubusercontent.com/45564317/170285068-c9450884-089d-455f-9c72-11238b8a1885.png)

Which explains the command `SetOutputConfiguration` in detail.

So I think we can just update the values mentioned above to be configurable parameteres.

**Comment by traversaro** [comment]
Good analysis!

**Comment by HosameldinMohamed** [comment]
It seems also that the main loop `sensorReadLoop` is also running every `10ms`, see

https://github.com/robotology/yarp-device-xsensmt/blob/7b9425c87797fb4f443bcab6838f755faece8472/xsensmt/XsensMT.cpp#L324

**Comment by traversaro** [comment]
> It seems also that the main loop `sensorReadLoop` is also running every `10ms`, see
> 
> https://github.com/robotology/yarp-device-xsensmt/blob/7b9425c87797fb4f443bcab6838f755faece8472/xsensmt/XsensMT.cpp#L324

Note that those are `std::chrono::microseconds(10)`, i.e. 10 us, not 10 ms.

**Comment by HosameldinMohamed** [comment]
We may configure one parameter `period` or `frequency`, that the device `xsnensmt` takes and sets the values in https://github.com/robotology/yarp-device-xsensmt/issues/33#issuecomment-1137322168


> Note that those are `std::chrono::microseconds(10)`, i.e. 10 us, not 10 ms.

Oh my bad!, then it's almost continuous as you said!

**Comment by traversaro** [comment]
> > We may configure one parameter `period` or `frequency`, that the device `xsnensmt` takes and sets the values in [#33 (comment)](https://github.com/robotology/yarp-device-xsensmt/issues/33#issuecomment-1137322168)
> 
> I have a question, how to set the parameters of the device `xsensmt` in case it's called as a `subdevice`? As we do in [this example](https://github.com/ami-iit/robots-configuration/blob/562d836455fc5f5eb3ad3c17e11e9da8dfbb275d/iRonCub-Mk1/hardware/inertials/waist-inertial.xml)?
> 
> ```
> <?xml version="1.0" encoding="UTF-8" ?>
> <!DOCTYPE devices PUBLIC "-//YARP//DTD yarprobotinterface 3.0//EN" "http://www.yarp.it/DTD/yarprobotinterfaceV3.0.dtd">
> 
> 
>  <device xmlns:xi="http://www.w3.org/2001/XInclude" name="xsens_inertial" type="inertial">
>       <param name="name">  /icub/xsens_inertial  </param>
>       <param name="period">  0.002  </param>
>       <param name="subdevice">  xsensmt  </param>
>       <param name="serial">  /dev/ttyXsens   </param>
> </device>
> ```

In that case, all parameters under the device tag are passed both to the Network Wrapper Server (`inertial`) and to the hardware device (`xsensmt`). So just add any `xsensmt`parameter to the parameter list, it will be ignored by `inertial` and used by `xsensmt`.

**Comment by gabrielenava** [comment]
>We are testing this with IMU MTi-100 (@traversaro can you confirm),

while testing on the robot with @HosameldinMohamed we noted that the device is recognized as IMU MTi-300
