### ISSUE TITLE
Create a new release out of the current state

### ISSUE THREAD

**Issue by HosameldinMohamed** [robotology/yarp-device-xsensmt#45]
The latest release [v0.2.2](https://github.com/robotology/yarp-device-xsensmt/releases/tag/v0.2.2) is from November 2022, and many updates have been added since then.

There have been many cases where a fresh install via `robotology-superbuild` didn't work with some new devices, and the users had to switch to `master` in order to get it running, but it cost them some debugging time before figuring that out.

CC @gabrielenava @davidegorbani @GiulioRomualdi @G-Cervettini @traversaro

**Comment by traversaro** [comment]
This should fix it: https://github.com/robotology/yarp-device-xsensmt/pull/46, I also took the occasion to re-license the code.

**Comment by traversaro** [comment]
> There have been many cases where a fresh install via `robotology-superbuild` didn't work with some new devices, and the users had to switch to `master` in order to get it running, but it cost them some debugging time before figuring that out.

In the future, feel free to report the problem at the first case.

**Comment by HosameldinMohamed** [comment]
Thanks @traversaro!
